In [1]:
import numpy as np
import pandas as py
import keras as kp
import sklearn
import matplotlib.pyplot as plt

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

In [2]:
x_train=train_datagen.flow_from_directory(r"D:\asl_project",target_size=(64,64),batch_size=32,class_mode='binary')

NameError: name 'train_datagen' is not defined

In [6]:
x_train.class_indices

{'A': 0, 'E': 1, 'I': 2, 'O': 3, 'U': 4}

In [7]:
cnn_model=Sequential()

Conv Layer

In [8]:
cnn_model.add(Conv2D(32,(3,3),input_shape=(64,64,3),activation='relu'))


Max Pooling

In [9]:
cnn_model.add(MaxPooling2D(pool_size=(2,2)))

Flattening

In [10]:
cnn_model.add(Flatten())

In [11]:
#hidden layer
cnn_model.add(Dense(100,activation='relu'))

In [12]:
cnn_model.add(Dense(100,activation='relu'))

In [13]:
#output layer
cnn_model.add(Dense(5,activation='sigmoid'))

In [14]:
#compiler
cnn_model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy','precision','recall'])

In [18]:
cnn_model.fit_generator(x_train,epochs=2,nb_val_samples=200)

TypeError: fit_generator() got an unexpected keyword argument 'nb_val_samples'

In [16]:
cnn_model.save("sign1.h5")

In [17]:
from keras.models import load_model
import numpy as np
import cv2
model=load_model("sign1.h5")

In [18]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
frame=plt.imread(r"E:\asl\train\I\I10.jpg")

In [20]:
from skimage.transform import resize
def detect(frame):
    try:
        print(frame.shape)
        img=resize(frame,(64,64))
        img=np.expand_dims(img,axis=0)
        print(img.shape)
        if(np.max(img)):
            img=img/255.0
            prediction=model.predict_classes(img)
            print(prediction)
    except AttributeError:
        print("shape not found")
detect(frame)

(200, 200, 3)


C:\Users\Ameesha\Anaconda3\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "


(1, 64, 64, 3)
[1]


In [21]:
cnn_model.save("sign1.h5")

In [28]:

import numpy as np
from keras.preprocessing import image

from tkinter import *
from PIL import ImageTk, Image
from tkinter import filedialog
import os
from keras.models import load_model
classifier = load_model('sign1.h5')
classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
root = Tk()
root.geometry("550x300+300+150")
root.resizable(width=True, height=True)

def openfn():
    filename = filedialog.askopenfilename(title='open')
    return filename
def open_img():
    x = openfn()
    test_image = image.load_img(x, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = classifier.predict_classes(test_image)
    print(result)
    print(test_image)
    index=["A","I","E","O","U"]
    label = Label( root, text="Prediction : "+index[result[0]])
    label.pack()
    img = Image.open(x)
    img = img.resize((250, 250), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(img)
    panel = Label(root, image=img)
    panel.image = img
    panel.pack()

btn = Button(root, text='open image', command=open_img).pack()

root.mainloop()


[0]
[[[[  0.   1. 228.]
   [ 13.   6. 184.]
   [  9.   9. 183.]
   ...
   [ 18.   4. 187.]
   [  5.   6. 176.]
   [  9.   4. 208.]]

  [[ 14.   7. 183.]
   [ 60.  49.   3.]
   [ 66.  51.  22.]
   ...
   [193. 172. 125.]
   [205. 185. 158.]
   [184. 168. 207.]]

  [[ 12.   5. 181.]
   [ 60.  57.  26.]
   [ 63.  49.  36.]
   ...
   [196. 172. 148.]
   [200. 178. 154.]
   [188. 172. 237.]]

  ...

  [[  7.   7. 183.]
   [147. 139. 116.]
   [139. 143. 118.]
   ...
   [155. 136. 132.]
   [146. 138. 117.]
   [140. 124. 199.]]

  [[  5.  11. 187.]
   [138. 138. 126.]
   [134. 144. 135.]
   ...
   [150. 136. 125.]
   [145. 138. 120.]
   [137. 125. 191.]]

  [[  7.   6. 208.]
   [130. 133. 184.]
   [124. 134. 195.]
   ...
   [142. 130. 202.]
   [135. 130. 197.]
   [124. 118. 240.]]]]
